import { randomUUID } from "node:crypto";
import { JSON_BODY_LIMIT_BYTES, WEBHOOK_BODY_LIMIT_BYTES } from "./constants";
import { digestRequest, hashSourceIp, parseClaim, sourceIpBucketFromRequest } from "./crypto";
import { productionClerkAuth, requireClerkSubject, type ClerkAuthPort } from "./auth";
import { isW1Error, mapUnexpectedError, w1Error } from "./errors";
import { requireInternalBearer } from "./internal-auth";
import { validateIdempotencyKey } from "./idempotency";
import { createProductionW1ScopeFactory, createW1Services, type W1RequestScope, type W1RequestScopeFactory } from "./services";
export class StrictJsonError extends Error {}
class Parser { private index = 0; constructor(private readonly text: string) {} parse() { const value = this.value(); this.space(); if (this.index !== this.text.length) throw new StrictJsonError(); if (!value || Array.isArray(value) || typeof value !== "object") throw new StrictJsonError(); return value as Record<string, unknown>; } private space() { while (/\s/.test(this.text[this.index] ?? "")) this.index++; } private value(): unknown { this.space(); const c = this.text[this.index]; if (c === "{") return this.object(); if (c === "[") return this.array(); if (c === '"') return this.string(); if (c === "t" && this.text.slice(this.index, this.index + 4) === "true") { this.index += 4; return true; } if (c === "f" && this.text.slice(this.index, this.index + 5) === "false") { this.index += 5; return false; } if (c === "n" && this.text.slice(this.index, this.index + 4) === "null") { this.index += 4; return null; } const value = this.text.slice(this.index).match(/^-?(?:0|[1-9][0-9]*)(?:\.[0-9]+)?(?:[eE][+-]?[0-9]+)?/); if (value) { this.index += value[0].length; const number = Number(value[0]); if (!Number.isFinite(number)) throw new StrictJsonError(); return number; } throw new StrictJsonError(); } private object() { const result: Record<string, unknown> = {}; const keys = new Set<string>(); this.index++; this.space(); if (this.text[this.index] === "}") { this.index++; return result; } while (true) { this.space(); if (this.text[this.index] !== '"') throw new StrictJsonError(); const key = this.string(); if (keys.has(key)) throw new StrictJsonError(); keys.add(key); this.space(); if (this.text[this.index++] !== ":") throw new StrictJsonError(); result[key] = this.value(); this.space(); const separator = this.text[this.index++]; if (separator === "}") return result; if (separator !== ",") throw new StrictJsonError(); } } private array() { const result: unknown[] = []; this.index++; this.space(); if (this.text[this.index] === "]") { this.index++; return result; } while (true) { result.push(this.value()); this.space(); const separator = this.text[this.index++]; if (separator === "]") return result; if (separator !== ",") throw new StrictJsonError(); } } private string() { const start = this.index; this.index++; let escaped = false; while (this.index < this.text.length) { const c = this.text[this.index++]; if (!escaped && c === '"') { try { return JSON.parse(this.text.slice(start, this.index)) as string; } catch { throw new StrictJsonError(); } } if (!escaped && c === "\\") escaped = true; else escaped = false; if (c.charCodeAt(0) < 0x20) throw new StrictJsonError(); } throw new StrictJsonError(); } }
export async function readStrictJsonObject(request: Request, limit = JSON_BODY_LIMIT_BYTES) { const reader = request.body?.getReader(); const chunks: Uint8Array[] = []; let length = 0; if (reader) { while (true) { const item = await reader.read(); if (item.done) break; length += item.value.byteLength; if (length > limit) { await reader.cancel(); throw new StrictJsonError(); } chunks.push(item.value); } } const bytes = new Uint8Array(length); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.length; } let text: string; try { text = new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw new StrictJsonError(); } return new Parser(text).parse(); }
export async function readBoundedWebhookText(request: Request, limit = WEBHOOK_BODY_LIMIT_BYTES): Promise<string> {
  const declared = request.headers.get("content-length");
  if (declared !== null && (!/^(?:0|[1-9][0-9]*)$/.test(declared) || !Number.isSafeInteger(Number(declared)) || Number(declared) > limit)) throw new StrictJsonError();
  const reader = request.body?.getReader(); const chunks: Uint8Array[] = []; let length = 0;
  if (reader) {
    while (true) { const item = await reader.read(); if (item.done) break; length += item.value.byteLength; if (length > limit) { await reader.cancel(); throw new StrictJsonError(); } chunks.push(item.value); }
  }
  const bytes = new Uint8Array(length); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; }
  try { return new TextDecoder("utf-8", { fatal: true }).decode(bytes); } catch { throw new StrictJsonError(); }
}
const canonicalUuid = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const requestIdUuid = new RegExp(canonicalUuid.source, "i");
export const makeRequestId = (request: Request) => { const candidate = request.headers.get("x-request-id"); return candidate && requestIdUuid.test(candidate) ? candidate.toLowerCase() : randomUUID(); };
const headers = (requestId: string, extra?: HeadersInit) => ({ "content-type": "application/json", "cache-control": "no-store", "x-request-id": requestId, ...extra });
export const jsonResponse = (body: unknown, requestId: string, status = 200, extra?: HeadersInit) => new Response(JSON.stringify(body), { status, headers: headers(requestId, extra) });
export const errorResponse = (error: unknown, requestId: string, routeClass: "billing" | "entitlement" | "claim" | "webhook" = "claim") => { const known = isW1Error(error) ? error : mapUnexpectedError(routeClass); const extra = known.retryAfter ? { "retry-after": String(known.retryAfter) } : undefined; return jsonResponse({ error: { code: known.code, message: known.message, requestId } }, requestId, known.status, extra); };
const exact = (value: Record<string, unknown>, keys: string[]) => Object.keys(value).length === keys.length && keys.every((key) => Object.hasOwn(value, key));
export interface W1HttpHandlers { checkout(request: Request): Promise<Response>; entitlement(request: Request): Promise<Response>; issueClaim(request: Request): Promise<Response>; revokeClaim(request: Request, context: { params: Promise<{ claim_id: string }> }): Promise<Response>; reissueClaim(request: Request, context: { params: Promise<{ claim_id: string }> }): Promise<Response>; redeemClaim(request: Request): Promise<Response>; webhook(request: Request): Promise<Response>; }
const closeScope = async (scope: W1RequestScope | undefined): Promise<void> => { try { await scope?.close(); } catch { /* A response has already been determined. */ } };
export function createW1HttpHandlers(factory: W1RequestScopeFactory = createProductionW1ScopeFactory(), clerk: ClerkAuthPort = productionClerkAuth): W1HttpHandlers {
  return {
    checkout: async (request) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const subject = await requireClerkSubject(clerk); const key = validateIdempotencyKey(request.headers.get("idempotency-key")); let body: Record<string, unknown>; try { body = await readStrictJsonObject(request); } catch { throw w1Error("invalid_checkout_request"); } const digest = digestRequest("POST", new URL(request.url).pathname, body); const checkoutScope = await factory.create("checkout"); scope = checkoutScope; const services = createW1Services({ repository: checkoutScope.repository, checkoutAuthority: checkoutScope.checkoutAuthority, checkoutStripe: checkoutScope.checkoutStripe }); const replay = await services.inspectIdempotency(subject, "/api/billing/checkout", key, digest); if (replay) return jsonResponse(replay, requestId); if (!exact(body, ["product"]) || body.product !== "tester") throw w1Error("invalid_checkout_request"); return jsonResponse(await services.checkout(subject, key, digest), requestId); } catch (error) { return errorResponse(error, requestId, "billing"); } finally { await closeScope(scope); } },
    entitlement: async (request) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const subject = await requireClerkSubject(clerk); if (new URL(request.url).search || ["x-user-id", "x-clerk-user-id", "x-clerk-subject", "x-subject"].some((name) => request.headers.has(name))) throw w1Error("invalid_selector"); const reader = request.body?.getReader(); if (reader) { while (true) { const chunk = await reader.read(); if (chunk.done) break; if (chunk.value.byteLength) { await reader.cancel(); throw w1Error("invalid_selector"); } } await reader.cancel(); } scope = await factory.create("entitlement"); return jsonResponse(await createW1Services({ repository: scope.repository }).getEntitlement(subject), requestId); } catch (error) { return errorResponse(error, requestId, "entitlement"); } finally { await closeScope(scope); } },
    issueClaim: async (request) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const subject = await requireClerkSubject(clerk); const key = validateIdempotencyKey(request.headers.get("idempotency-key")); const body = await readStrictJsonObject(request); const digest = digestRequest("POST", new URL(request.url).pathname, body); if (!exact(body, [])) throw w1Error("invalid_request"); const claimScope = await factory.create("claim"); scope = claimScope; const result = await createW1Services({ repository: claimScope.repository, claimPepper: claimScope.claimPepper, rateLimitPepper: claimScope.rateLimitPepper }).issueClaim(subject, key, digest, hashSourceIp(sourceIpBucketFromRequest(request.headers), claimScope.rateLimitPepper)); return jsonResponse(result, requestId, 201); } catch (error) { return errorResponse(error, requestId); } finally { await closeScope(scope); } },
    revokeClaim: async (request, context) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const subject = await requireClerkSubject(clerk); const claimId = (await context.params).claim_id; if (!canonicalUuid.test(claimId)) throw w1Error("invalid_request"); const key = validateIdempotencyKey(request.headers.get("idempotency-key")); const body = await readStrictJsonObject(request); const digest = digestRequest("POST", new URL(request.url).pathname, body); if (!exact(body, ["reason"]) || body.reason !== "delivery_uncertain") throw w1Error("invalid_request"); scope = await factory.create("claim"); return jsonResponse(await createW1Services({ repository: scope.repository }).revokeClaim(subject, claimId, key, digest), requestId); } catch (error) { return errorResponse(error, requestId); } finally { await closeScope(scope); } },
    reissueClaim: async (request, context) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const subject = await requireClerkSubject(clerk); const claimId = (await context.params).claim_id; if (!canonicalUuid.test(claimId)) throw w1Error("invalid_request"); const key = validateIdempotencyKey(request.headers.get("idempotency-key")); const body = await readStrictJsonObject(request); const digest = digestRequest("POST", new URL(request.url).pathname, body); if (!exact(body, ["reason"]) || body.reason !== "delivery_uncertain") throw w1Error("invalid_request"); const claimScope = await factory.create("claim"); scope = claimScope; const result = await createW1Services({ repository: claimScope.repository, claimPepper: claimScope.claimPepper, rateLimitPepper: claimScope.rateLimitPepper }).reissueClaim(subject, claimId, key, digest, hashSourceIp(sourceIpBucketFromRequest(request.headers), claimScope.rateLimitPepper)); return jsonResponse(result, requestId, 201); } catch (error) { return errorResponse(error, requestId); } finally { await closeScope(scope); } },
    redeemClaim: async (request) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { const redeemScope = await factory.create("redeem"); scope = redeemScope; requireInternalBearer(request.headers, redeemScope.internalBearer); const body = await readStrictJsonObject(request); if (!exact(body, ["claim"]) || typeof body.claim !== "string" || !parseClaim(body.claim)) throw w1Error("invalid_request"); return jsonResponse(await createW1Services({ repository: redeemScope.repository, claimPepper: redeemScope.claimPepper }).redeemClaim(body.claim), requestId); } catch (error) { if (isW1Error(error) && error.code === "claim_not_found") return new Response(JSON.stringify({ code: "claim_not_found", message: "Claim unavailable." }), { status: 404, headers: headers(requestId) }); return errorResponse(error, requestId); } finally { await closeScope(scope); } },
    webhook: async (request) => { const requestId = makeRequestId(request); let scope: W1RequestScope | undefined; try { let raw: string; try { raw = await readBoundedWebhookText(request); } catch { throw w1Error("invalid_webhook"); } const signature = request.headers.get("stripe-signature"); if (!signature) throw w1Error("invalid_webhook"); const webhookScope = await factory.create("webhook"); scope = webhookScope; const envelope = webhookScope.webhookStripe.verifyWebhook(raw, signature); return jsonResponse(await createW1Services({ repository: webhookScope.repository, webhookStripe: webhookScope.webhookStripe, logger: webhookScope.webhookLogger }).handleWebhook(envelope, requestId), requestId); } catch (error) { return errorResponse(isW1Error(error) ? error : w1Error("invalid_webhook"), requestId, "webhook"); } finally { await closeScope(scope); } },
  };
}
export const w1Http = createW1HttpHandlers();
