import { STRIPE_EVENT_PRECEDENCE, SUPPORTED_STRIPE_EVENTS, type EntitlementStatus, type SupportedStripeEventType } from "./constants";
import type { StripeAuthorityBundle, VerifiedStripeEnvelope } from "./stripe";
export type WebhookDisposition = "processed" | "ignored" | "terminal_failed" | "retryable_failed";
export const classifySupportedEvent = (type: string): SupportedStripeEventType | null => (SUPPORTED_STRIPE_EVENTS as readonly string[]).includes(type) ? type as SupportedStripeEventType : null;
export function extractAuthorityReference(envelope: VerifiedStripeEnvelope) { const value = envelope.object; return { sessionId: typeof value.id === "string" ? value.id : "", customerId: typeof value.customer === "string" ? value.customer : null, subscriptionId: typeof value.subscription === "string" ? value.subscription : null }; }
export function mapSubscriptionStatus(status: string): Exclude<EntitlementStatus, "inactive"> | null { if (status === "active" || status === "trialing") return "active"; if (status === "incomplete") return "pending"; if (status === "past_due" || status === "unpaid") return "past_due"; if (["incomplete_expired", "canceled", "paused"].includes(status)) return "revoked"; return null; }
export function compareEventTuple(left: { createdAt: Date; precedence: number; id: string }, right: { createdAt: Date; precedence: number; id: string }) { const date = left.createdAt.getTime() - right.createdAt.getTime(); if (date) return date; const precedence = left.precedence - right.precedence; if (precedence) return precedence; return left.id === right.id ? 0 : left.id < right.id ? -1 : 1; }
export function evaluateWebhookAuthority(envelope: VerifiedStripeEnvelope, authority: StripeAuthorityBundle) { const supported = classifySupportedEvent(envelope.type); if (!supported) return { disposition: "ignored" as WebhookDisposition, supported: null, status: null }; if (!authority.valid) return { disposition: "terminal_failed" as WebhookDisposition, supported, status: null, failureCode: authority.failureCode }; if (supported === "checkout.session.completed") return { disposition: "processed" as WebhookDisposition, supported, status: "pending" as const }; if (supported === "invoice.paid") return { disposition: "processed" as WebhookDisposition, supported, status: "active" as const }; if (supported === "invoice.payment_failed") return { disposition: "processed" as WebhookDisposition, supported, status: "past_due" as const }; const mapped = mapSubscriptionStatus(authority.status ?? ""); return { disposition: "processed" as WebhookDisposition, supported, status: mapped === null ? null : supported === "customer.subscription.deleted" ? "revoked" as const : mapped }; }
export const eventPrecedence = (type: SupportedStripeEventType) => STRIPE_EVENT_PRECEDENCE[type];
